name: Test
on: [push]
jobs:
    Test:
        runs-on: "ubuntu-latest"
        steps:
            - name: "Checkout repository"
              uses: "actions/checkout@v2"
            - run: |
                source setup.sh
                python3 -m unittest discover tests
    Run:
        runs-on: "ubuntu-latest"
        needs: Test
        steps:
            - run: |
                source setup.sh
                python3 -m pip install -r requirements.txt
                mkdir -p data
                python3 run_all_strategies.py --ngames=100
    Plot:
        runs-on: "ubuntu-latest"
        needs: Run
        steps:
            - run: |
                source setup.sh
                python3 -m pip install -r requirements.txt
                python3 core/plotting/strategy_comparisons.py -i data/output.csv
